### PR TITLE
chore: Sync commits from old GitLab repo 20240506

### PR DESCRIPTION
**Pull request by hcnp**
Synced with these commands:
```bash
./implementationguide/sync-to-github.sh implementationguide implementation-guide 5b7beab787d43fb361f6e89ca9fe96a509c3a91d..HEAD
```

This is the difference currently because of this commit: 7a584f009a45bc533b41d6d584a991063c7e3bb5
```diff
> diff -rwu implementation-guide/input/ implementationguide/fsh-content/input
diff -rwu implementation-guide/input/resources/SearchParameter-ehealth-communication-search-restrictionCategory.json implementationguide/fsh-content/input/resources/SearchParameter-ehealth-communication-search-restrictionCategory.json
--- implementation-guide/input/resources/SearchParameter-ehealth-communication-search-restrictionCategory.json	2024-01-26 17:26:35.882016824 +0100
+++ implementationguide/fsh-content/input/resources/SearchParameter-ehealth-communication-search-restrictionCategory.json	2023-08-14 11:12:38.470166000 +0200
@@ -10,7 +10,7 @@
         "Communication"
     ],
     "type": "token",
-    "description": "Search parameter for finding communication based on restriction category",
+    "description": "Search parameter for finding communication based on CareTeam recipient",
     "expression": "Communication.extension('http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-restriction-category')",
     "xpathUsage": "normal"
 }
\ No newline at end of file
```

### CODE REVIEW

**Comment by jkiddo** [comment]
Ill need @ohetrifork 's eyes on it as well.

**Comment by ohetrifork** [comment]
@cobotrifork looks like you are the man behind the commit mentioned above?

**Comment by cobotrifork** [comment]
> @cobotrifork looks like you are the man behind the commit mentioned above?

That's true, should I also commit it on gitlab orr?

**Comment by ohetrifork** [comment]
> > @cobotrifork looks like you are the man behind the commit mentioned above?
> 
> That's true, should I also commit it on gitlab orr?

I guess we should just make sure that the github repo contains what we want. If it looks good to you, then it should be fine

**Comment by cobotrifork** [comment]
@ohetrifork I think that looks good, it is nothing big, just wanted to make sure that description text said restriction category

**Review by tyfoni-systematic — APPROVED** [review]

**Pull request merged**
