### PR TITLE
chore: Sync commits from old GitLab repo 20240103

### PR DESCRIPTION
**Pull request by hcnp**
Sync commits from old GitLab repo: https://gitlab.admin.ehealth.sundhed.dk/common/implementationguide

Done with this new script: https://gitlab.admin.ehealth.sundhed.dk/common/implementationguide/-/merge_requests/374

Synced with this hash range: acd9f5d35d43ea0511526b359e1274de0ae7f02d..HEAD

### CODE REVIEW

**Review by jkiddo — APPROVED** [review]
LGTM

**Comment by jkiddo** [comment]
@esn-systematic & @tyfoni-systematic are explicitly requested on Slack as well

**Comment by jkiddo** [comment]
Wait ... everything that is located in this PR under fsh-content/input should be moved to /input

**Review by jkiddo — CHANGES_REQUESTED** [review]
Wait ... everything that is located in this PR under fsh-content/input should be moved to /input

**Comment by hcnp** [comment]
> Wait ... everything that is located in this PR under fsh-content/input should be moved to /input

Ah. Good point. I'll do that.

**Comment by hcnp** [comment]
> Wait ... everything that is located in this PR under fsh-content/input should be moved to /input

I've moved the changes in that folder to the new location. I'm a bit confused about the /template folder which does not exist in the old repo.

**Comment by jkiddo** [comment]
I'll have a look

**Comment by tyfoni-systematic** [comment]
I have tried to compare the input folder of this branch with the corresponding folder in the master branch (https://gitlab.admin.ehealth.sundhed.dk/common/implementationguide).
But I dont think they agree (see below). This may be because there are changes after the sync was created. But I have failed to pinpoint which commit the sync was made from.

```
diff -r -w implementation-guide/input/ implementationguide/fsh-content/input
Only in implementationguide/fsh-content/input/fsh: build
diff -r -w implementation-guide/input/fsh/ehealth-activitydefinition.fsh implementationguide/fsh-content/input/fsh/ehealth-activitydefinition.fsh
10a11
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 0..1
Only in implementationguide/fsh-content/input/fsh: ehealth-ext-sharingApprovalPolicy.fsh
diff -r -w implementation-guide/input/fsh/ehealth-questionnaire.fsh implementationguide/fsh-content/input/fsh/ehealth-questionnaire.fsh
17a18
> * item obeys only-one-sliderStepValue-type-per-item and only-type-integer-if-sliderStepValue-is-integer
22a24
> * item.extension contains ehealth-questionnaire-sliderStepValueDecimal named questionnaire-sliderStepValueDecimal 0..1
37a40,46
> Extension: ehealth-questionnaire-sliderStepValueDecimal
> Title:     "Slider Step-value Decimal"
> Description: "Defines a decimal number step-value for the slider in the questionnaire."
> * . ^short = "The slider step-value as decimal-number"
> * value[x] only decimal
> * valueDecimal 1..1
>
122a132,141
>
> Invariant:   only-one-sliderStepValue-type-per-item
> Description: "Only one sliderStepValue type can be used per item, either decimal or integer, not both."
> Expression:  "(( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists().not())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists().not()))"
> Severity:    #error
>
> Invariant:   only-type-integer-if-sliderStepValue-is-integer
> Description: "If the type is integer, then the sliderStepValue must also be an integer."
> Expression:  "type = 'integer' implies extension.where(url ='http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists()"
> Severity:    #error
diff -r -w implementation-guide/input/fsh/ehealth-servicerequest.fsh implementationguide/fsh-content/input/fsh/ehealth-servicerequest.fsh
7a8
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 0..1
diff -r -w implementation-guide/input/fsh/ehealth-task.fsh implementationguide/fsh-content/input/fsh/ehealth-task.fsh
27a28
> * extension contains ehealth-resolved-timing named resolvedTiming 0..1
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md
35a36,39
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing
> of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically.
> The value in the ActivityDefinition function as a template assigned and adaptable to a particular Patient in a similar element in the
> ServiceRequest.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md
67a68,72
>
> ### Used for manual approval of measurement sharing
> The element `assessorOrganization` is automatically set by the infrastructure to reflect the organizational context of the assessor who performed the assessment, when a ClinicalImpression is created to indicate the approval of document sharing.
> * In the case of a manual approval, the element `assessorOrganization` will automatically be set to the organizational context of the Practitioner who performed the assessment.
> * In the case of an automated approval, the element `assessorOrganization` will automatically be set to the CarePlan.author if possible, else it will be the EpisodeOfCare.caremanagerOrganization.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md
11a12
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically. The initial value will be inherited from the ActivityDefinition referenced in `definition`, but can subsequently be adapted for the particular Patient by adjusting the ServiceRequest.
diff -r -w implementation-guide/input/pagecontent/changelog.md implementationguide/fsh-content/input/pagecontent/changelog.md
10a11
> - Added http://ehealth.sundhed.dk/cs/measurement-sharing-approval-policies
16a18
> - Added http://ehealth.sundhed.dk/vs/measurement-sharing-approval-policies
21a24
> - Updated ValueSet-ehealth-questionnaire-item-control to contain code `slider`
22a26
> - Added http://ehealth.sundhed.dk/ConceptMap/activitydefinition-code-to-perform-sharing The map controls whether the sharingApprovalPolicy-field should be set on the given resource.
24,35c28
<
< ## 2.11.0 (2023-11-24)
<
< ### General changes
<
< ### Custom operations
< #### System operations
< #### Instance operations
< ### Code systems
< ### ValueSets
< ### ConceptMaps
< ### Resource/profile changes
---
> - Added extension ehealth-ext-sharingApprovalPolicy to ActivityDefinition and ServiceRequest
37c30,31
<
---
> - Added invariant to Questionnaire that only allows one sliderStepValue at a time
> - Added extention ehealth-resolved-timing to Task
Only in implementationguide/fsh-content/input/resources: CodeSystem-ehealth-measurement-sharing-approval-policies.json
Only in implementationguide/fsh-content/input/resources: ConceptMap-ehealth.sundhed.dk-ConceptMap-activitydefinition-code-to-perform-sharing.json
diff -r -w implementation-guide/input/resources/ValueSet-ehealth-questionnaire-item-control.json implementationguide/fsh-content/input/resources/ValueSet-ehealth-questionnaire-item-control.json
39a40,43
>           },
>           {
>             "code": "slider",
>             "display": "Slider"
Only in implementationguide/fsh-content/input/resources: ValueSet-ehealth-sharing-approval-policies.json
```

**Review by tyfoni-systematic — COMMENTED** [review]
I have tried to compare the input folder of this branch with the corresponding folder in the master branch (https://gitlab.admin.ehealth.sundhed.dk/common/implementationguide).
But I dont think they agree (see below). This may be because there are changes after the sync was created. But I have failed to pinpoint which commit the sync was made from.

```
diff -r -w implementation-guide/input/ implementationguide/fsh-content/input
Only in implementationguide/fsh-content/input/fsh: build
diff -r -w implementation-guide/input/fsh/ehealth-activitydefinition.fsh implementationguide/fsh-content/input/fsh/ehealth-activitydefinition.fsh
10a11
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 0..1
Only in implementationguide/fsh-content/input/fsh: ehealth-ext-sharingApprovalPolicy.fsh
diff -r -w implementation-guide/input/fsh/ehealth-questionnaire.fsh implementationguide/fsh-content/input/fsh/ehealth-questionnaire.fsh
17a18
> * item obeys only-one-sliderStepValue-type-per-item and only-type-integer-if-sliderStepValue-is-integer
22a24
> * item.extension contains ehealth-questionnaire-sliderStepValueDecimal named questionnaire-sliderStepValueDecimal 0..1
37a40,46
> Extension: ehealth-questionnaire-sliderStepValueDecimal
> Title:     "Slider Step-value Decimal"
> Description: "Defines a decimal number step-value for the slider in the questionnaire."
> * . ^short = "The slider step-value as decimal-number"
> * value[x] only decimal
> * valueDecimal 1..1
>
122a132,141
>
> Invariant:   only-one-sliderStepValue-type-per-item
> Description: "Only one sliderStepValue type can be used per item, either decimal or integer, not both."
> Expression:  "(( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists().not())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists().not()))"
> Severity:    #error
>
> Invariant:   only-type-integer-if-sliderStepValue-is-integer
> Description: "If the type is integer, then the sliderStepValue must also be an integer."
> Expression:  "type = 'integer' implies extension.where(url ='http://hl7.org/fhir/StructureDefinition/questionnaire-sliderStepValue').value.exists()"
> Severity:    #error
diff -r -w implementation-guide/input/fsh/ehealth-servicerequest.fsh implementationguide/fsh-content/input/fsh/ehealth-servicerequest.fsh
7a8
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 0..1
diff -r -w implementation-guide/input/fsh/ehealth-task.fsh implementationguide/fsh-content/input/fsh/ehealth-task.fsh
27a28
> * extension contains ehealth-resolved-timing named resolvedTiming 0..1
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md
35a36,39
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing
> of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically.
> The value in the ActivityDefinition function as a template assigned and adaptable to a particular Patient in a similar element in the
> ServiceRequest.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md
67a68,72
>
> ### Used for manual approval of measurement sharing
> The element `assessorOrganization` is automatically set by the infrastructure to reflect the organizational context of the assessor who performed the assessment, when a ClinicalImpression is created to indicate the approval of document sharing.
> * In the case of a manual approval, the element `assessorOrganization` will automatically be set to the organizational context of the Practitioner who performed the assessment.
> * In the case of an automated approval, the element `assessorOrganization` will automatically be set to the CarePlan.author if possible, else it will be the EpisodeOfCare.caremanagerOrganization.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md
11a12
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically. The initial value will be inherited from the ActivityDefinition referenced in `definition`, but can subsequently be adapted for the particular Patient by adjusting the ServiceRequest.
diff -r -w implementation-guide/input/pagecontent/changelog.md implementationguide/fsh-content/input/pagecontent/changelog.md
10a11
> - Added http://ehealth.sundhed.dk/cs/measurement-sharing-approval-policies
16a18
> - Added http://ehealth.sundhed.dk/vs/measurement-sharing-approval-policies
21a24
> - Updated ValueSet-ehealth-questionnaire-item-control to contain code `slider`
22a26
> - Added http://ehealth.sundhed.dk/ConceptMap/activitydefinition-code-to-perform-sharing The map controls whether the sharingApprovalPolicy-field should be set on the given resource.
24,35c28
<
< ## 2.11.0 (2023-11-24)
<
< ### General changes
<
< ### Custom operations
< #### System operations
< #### Instance operations
< ### Code systems
< ### ValueSets
< ### ConceptMaps
< ### Resource/profile changes
---
> - Added extension ehealth-ext-sharingApprovalPolicy to ActivityDefinition and ServiceRequest
37c30,31
<
---
> - Added invariant to Questionnaire that only allows one sliderStepValue at a time
> - Added extention ehealth-resolved-timing to Task
Only in implementationguide/fsh-content/input/resources: CodeSystem-ehealth-measurement-sharing-approval-policies.json
Only in implementationguide/fsh-content/input/resources: ConceptMap-ehealth.sundhed.dk-ConceptMap-activitydefinition-code-to-perform-sharing.json
diff -r -w implementation-guide/input/resources/ValueSet-ehealth-questionnaire-item-control.json implementationguide/fsh-content/input/resources/ValueSet-ehealth-questionnaire-item-control.json
39a40,43
>           },
>           {
>             "code": "slider",
>             "display": "Slider"
Only in implementationguide/fsh-content/input/resources: ValueSet-ehealth-sharing-approval-policies.json
```

**Comment by hcnp** [comment]
@tyfoni-systematic: Commits newer than c10f2144af24b8f93a7c560ce15e9ace707161b4 has not been synced yet in this branch.

**Comment by tyfoni-systematic** [comment]
> @tyfoni-systematic: Commits newer than [c10f214](https://github.com/fut-infrastructure/implementation-guide/commit/c10f2144af24b8f93a7c560ce15e9ace707161b4) has not been synced yet in this branch.

OK, if I make a branch from the commit I still find a difference:

```
 diff -r -w implementation-guide/input/ implementationguide/fsh-content/input
Only in implementationguide/fsh-content/input/fsh: build
diff -r -w implementation-guide/input/fsh/ehealth-activitydefinition.fsh implementationguide/fsh-content/input/fsh/ehealth-activitydefinition.fsh
10a11
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 1..1
Only in implementationguide/fsh-content/input/fsh: ehealth-ext-sharingApprovalPolicy.fsh
diff -r -w implementation-guide/input/fsh/ehealth-questionnaire.fsh implementationguide/fsh-content/input/fsh/ehealth-questionnaire.fsh
17a18
> * item obeys only-one-sliderStepValue-type-per-item
22a24
> * item.extension contains ehealth-questionnaire-sliderStepValueDecimal named questionnaire-sliderStepValueDecimal 0..1
37a40,46
> Extension: ehealth-questionnaire-sliderStepValueDecimal
> Title:     "Slider Step-value Decimal"
> Description: "Defines a decimal number step-value for the slider in the questionnaire."
> * . ^short = "The slider step-value as decimal-number"
> * value[x] only decimal
> * valueDecimal 1..1
>
122a132,136
>
> Invariant:   only-one-sliderStepValue-type-per-item
> Description: "Only one sliderStepValue type can be used per item, either decimal or integer, not both."
> Expression:  "(( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists()) and ( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValue').value.exists().not())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValue').value.exists())) or (( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValueDecimal').value.exists().not()) and ( extension.where(url = 'http://ehealth.sundhed.dk/fhir/StructureDefinition/ehealth-questionnaire-sliderStepValue').value.exists().not()))"
> Severity:    #error
diff -r -w implementation-guide/input/fsh/ehealth-servicerequest.fsh implementationguide/fsh-content/input/fsh/ehealth-servicerequest.fsh
7a8
> * extension contains ehealth-sharingApprovalPolicy named sharingApprovalPolicy 1..1
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md
35a36,39
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing
> of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically.
> The value in the ActivityDefinition function as a template assigned and adaptable to a particular Patient in a similar element in the
> ServiceRequest.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-clinicalimpression-intro.md
67a68,72
>
> ### Used for manual approval of measurement sharing
> The element `assessorOrganization` is automatically set by the infrastructure to reflect the organizational context of the assessor who performed the assessment, when a ClinicalImpression is created to indicate the approval of document sharing.
> * In the case of a manual approval, the element `assessorOrganization` will automatically be set to the organizational context of the Practitioner who performed the assessment.
> * In the case of an automated approval, the element `assessorOrganization` will automatically be set to the CarePlan.author if possible, else it will be the EpisodeOfCare.caremanagerOrganization.
diff -r -w implementation-guide/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md implementationguide/fsh-content/input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md
11a12
> * `ehealth-sharingApprovalPolicy` Selects whether the approval of publication to national document sharing of measurements (resource(s) resulting from conducting the activity) must be done manually or if it is done automatically. The initial value will be inherited from the ActivityDefinition referenced in `definition`, but can subsequently be adapted for the particular Patient by adjusting the ServiceRequest.
diff -r -w implementation-guide/input/pagecontent/changelog.md implementationguide/fsh-content/input/pagecontent/changelog.md
10a11
> - Added http://ehealth.sundhed.dk/cs/measurement-sharing-approval-policies
16a18
> - Added http://ehealth.sundhed.dk/vs/measurement-sharing-approval-policies
24,35c26
<
< ## 2.11.0 (2023-11-24)
<
< ### General changes
<
< ### Custom operations
< #### System operations
< #### Instance operations
< ### Code systems
< ### ValueSets
< ### ConceptMaps
< ### Resource/profile changes
---
> - Added extension ehealth-ext-sharingApprovalPolicy to ActivityDefinition and ServiceRequest
Only in implementationguide/fsh-content/input/resources: CodeSystem-ehealth-measurement-sharing-approval-policies.json
Only in implementationguide/fsh-content/input/resources: ValueSet-ehealth-sharing-approval-policies.json

```

**Comment by jkiddo** [comment]
@hcnp any progress?

**Comment by hcnp** [comment]
I can make a new sync. I'm not sure if the differences @tyfoni-systematic has found are significant. Should they be there or not?

**Comment by hcnp** [comment]
@tyfoni-systematic: I made an error in 24de69ed1eb9aab79f6702ad2bfe131f90d1e75a - Can you check again. The diff now reports no differences.

**Review by tyfoni-systematic — APPROVED** [review]

**Review by jkiddo — APPROVED** [review]

**Pull request merged**
